project:
  type: website
  resources:
    - images/python-logo.png
    - images/r-logo.png
    - images/code-icon.png

website:
  page-navigation: true
  title: "Build-a-Dashboard Workshop"
  description: "posit::conf(2024) - Build-a-Dashboard Workshop"

  repo-url: https://github.com/posit-conf-2024/quarto-dashboards
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#7A9857"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/posit-conf-2024/quarto-dashboards
        text: "GitHub"
      - icon: code-square
        href: https://posit.cloud
        text: "Posit Cloud"

    style: docked
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - href: setup.qmd
        text: Setup
      - section: "Modules"
        contents:
          - href: 1-hello-dashboards/index.qmd
          - href: 2-dashboard-components/index.qmd
          - href: 3-theming-styling/index.qmd
          - href: 4-parameters-interactivity-deployment/index.qmd


  page-footer:
    right: "This page is built with 💛 and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2024, Mine Çetinkaya-Rundel"
    background: "#7A9857"

format:
  html:
    theme:
      light: [cosmo, style/quarto-conf.scss]
      dark: [cosmo, style/quarto-conf.scss, style/dark.scss]
    linkcolor: "#589398"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto
  echo: true

editor: source
